name: Build and deploy Node.js app to Azure Web App - participant-web-25

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            # Step 1: Checkout the code
            - uses: actions/checkout@v4

            # Step 2: Set up Node.js version for the root
            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: "20.x"

            # Step 3: Install dependencies in the root directory
            - name: Install dependencies in root
              run: npm install

            # Step 4: Navigate to the frontend directory and install dependencies there
            - name: Install dependencies in frontend
              run: |
                  cd frontend
                  npm install

            # Step 5: Build the frontend (if applicable)
            - name: Build frontend
              env:
                  VITE_API_URL: https://particpant-web-25-backend-afbrfcb7d8e7hdcq.norwayeast-01.azurewebsites.net:443
              run: |
                  cd frontend
                  npm run build --if-present

            # Step 6: Upload only the frontend build output for deployment
            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: app-frontend
                  path: ./frontend/dist # Adjust this to your actual build output folder if necessary

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write # This is required for requesting the JWT

        steps:
            # Step 7: Download the artifact from the build job
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: app-frontend

            # Step 8: Log in to Azure
            - name: Login to Azure
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FC599DD607174723A66F9EFBB47E0DAC }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_55487918B3224FB3A0FA6A9E83E2498D }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_051F9C2D47DD440AAA7EB18EED1E4986 }}

            # Step 9: Deploy to Azure Web App
            - name: "Deploy to Azure Web App"
              uses: azure/webapps-deploy@v3
              id: deploy-to-webapp
              with:
                  app-name: "participant-web-25"
                  slot-name: "Production"
                  package: . # Ensure this is the correct path for the frontend build output
