name: Build and deploy frontend (Vite) to Azure Web App - participant-web-25

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_frontend:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build frontend
        run: |
          cd frontend
          npm install
          npm run build  # This will generate the 'dist' folder

      - name: Upload artifact for frontend deployment
        uses: actions/upload-artifact@v4
        with:
          name: app-frontend
          path: ./frontend/dist  # Upload the dist folder

  deploy:
    runs-on: ubuntu-latest
    needs: build_frontend
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: app-frontend

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FC599DD607174723A66F9EFBB47E0DAC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_55487918B3224FB3A0FA6A9E83E2498D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_051F9C2D47DD440AAA7EB18EED1E4986 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'participant-web-25'
          slot-name: 'Production'
          package: ./frontend/dist  # Deploy the dist folder
