name: Build and deploy Node.js backend to Azure Web App - participant-web-25-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_backend:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies
      - name: Install dependencies in backend
        run: |
          cd backend
          npm install

      # Compile TypeScript code
      - name: Build backend (Compile TypeScript)
        run: |
          cd backend
          npm run build  # This should generate the dist folder

      # List the backend directory to check if 'dist' exists
      - name: List backend directory after build
        run: |
          ls backend
          ls backend/dist

      # Upload the dist folder for deployment
      - name: Upload artifact for backend deployment
        uses: actions/upload-artifact@v4
        with:
          name: app-backend
          path: backend/dist  # Correct the path to point to backend/dist

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build_backend
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      # Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: app-backend
      
      # Log in to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FC599DD607174723A66F9EFBB47E0DAC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_55487918B3224FB3A0FA6A9E83E2498D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_051F9C2D47DD440AAA7EB18EED1E4986 }}

      # Deploy the compiled backend to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'participant-web-25-backend'  # Your Azure Web App name for backend
          slot-name: 'Production'
          package: backend/dist  # Deploy the dist folder
