name: Build and deploy Node.js backend to Azure Web App - participant-web-25-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_backend:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies
      - name: Install dependencies in backend
        run: |
          cd backend
          npm install  # Install both prod and dev dependencies

      # Compile TypeScript code
      - name: Build backend (Compile TypeScript)
        run: |
          cd backend
          npm run build  # Runs tsc and compiles the TypeScript code into JavaScript

      # Upload the dist folder for deployment
      - name: Upload artifact for backend deployment
        uses: actions/upload-artifact@v4
        with:
          name: app-backend
          path: ./backend/dist  # Upload the compiled JavaScript files (from dist or your outDir)

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build_backend
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      # Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: app-backend
      
      # Log in to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AEBFCA92A46E4988A768E1ADFD4EE2E9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8F01AB4AEAC243CCA489703199DCDEAE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A05054AB079A4D44B424A1D4659E2844 }}

      # Deploy the compiled backend to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'participant-web-25-backend'  # Azure Web App name for backend
          slot-name: 'Production'
          package: ./backend/dist  # Deploy the dist folder
