export const nations = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua & Deps',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Cape Verde',
    'Central African Rep',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Republic of the Congo',
    'Congo {Democratic Rep}',
    'Cook Islands',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'East Timor',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland {Republic}',
    'Israel',
    'Italy',
    'Ivory Coast',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Korea North',
    'Korea South',
    'Kosovo',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'North Macedonia',
    'Norway',
    'Oman',
    'Palestine',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russian Federation',
    'Rwanda',
    'St Kitts & Nevis',
    'St Lucia',
    'Saint Vincent & the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome & Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tonga',
    'Trinidad & Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Western Sahara',
    'Yemen',
    'Zambia',
    'Zimbabwe',
  ];
export const nationalities = [
    'Afghan',
    'Albanian',
    'Algerian',
    'American',
    'Andorran',
    'Angolan',
    'Antiguan or Barbudan',
    'Argentine',
    'Armenian',
    'Australian',
    'Austrian',
    'Azerbaijani',
    'Bahamian',
    'Bahraini',
    'Bangladeshi',
    'Barbadian',
    'Belarusian',
    'Belgian',
    'Belizean',
    'Beninese',
    'Bhutanese',
    'Bolivian',
    'Bosnian',
    'Botswanan',
    'Brazilian',
    'British',
    'Bruneian',
    'Bulgarian',
    'Burmese',
    'Burkinabé',
    'Burundian',
    'Cabo Verdean',
    'Cambodian',
    'Cameroonian',
    'Canadian',
    'Central African',
    'Chadian',
    'Chilean',
    'Chinese',
    'Colombian',
    'Comoran',
    'Congolese (Congo-Brazzaville)',
    'Congolese (Congo-Kinshasa)',
    'Cook islander',
    'Costa Rican',
    'Croatian',
    'Cuban',
    'Cypriot',
    'Czech',
    'Danish',
    'Djiboutian',
    'Dominican',
    'Dominican (Dominican Republic)',
    'Dutch',
    'Timorese',
    'Ecuadorean',
    'El Salvador / Salvadoran',
    'Egyptian',
    'Emirati',
    'Equatorial Guinean',
    'Eritrean',
    'Estonian',
    'Eswatini',
    'Ethiopian',
    'Fijian',
    'Filipino',
    'Finnish',
    'French',
    'Gabonese',
    'Gambian',
    'Georgian',
    'German',
    'Ghanaian',
    'Greek',
    'Grenadian',
    'Guatemalan',
    'Guinean',
    'Guinea-Bissauan',
    'Guyanese',
    'Haitian',
    'Honduran',
    'Hungarian',
    'Icelandic',
    'Indian',
    'Indonesian',
    'Iranian',
    'Iraqi',
    'Irish',
    'Israeli',
    'Italian',
    'Ivorian',
    'Jamaican',
    'Japanese',
    'Jordanian',
    'Kazakh',
    'Kenyan',
    'Kiribati',
    'Kosovar',
    'Kuwaiti',
    'Kyrgyz',
    'Laotian',
    'Latvian',
    'Lebanese',
    'Lesotho',
    'Liberian',
    'Libyan',
    'Liechtensteiner',
    'Lithuanian',
    'Luxembourger',
    'Macedonian',
    'Malagasy',
    'Malawian',
    'Malaysian',
    'Maldivian',
    'Malian',
    'Maltese',
    'Marshallese',
    'Mauritanian',
    'Mauritian',
    'Mexican',
    'Micronesian',
    'Moldovan',
    'Monacan',
    'Mongolian',
    'Montenegrin',
    'Moroccan',
    'Mozambican',
    'Namibian',
    'Nauruan',
    'Nepalese',
    'New Zealander',
    'Nicaraguan',
    'Nigerien',
    'Nigerian',
    'Niuean',
    'North Korean',
    'Norwegian',
    'Omani',
    'Pakistani',
    'Palauan',
    'Palestinian',
    'Panamanian',
    'Papua New Guinean',
    'Paraguayan',
    'Peruvian',
    'Polish',
    'Portuguese',
    'Qatari',
    'Romanian',
    'Russian',
    'Rwandan',
    'Sahrawi',
    'Saint Kitts and Nevis',
    'Saint Lucian',
    'Saint Vincentian',
    'Samoan',
    'San Marinese',
    'Sao Tomean',
    'Saudi',
    'Senegalese',
    'Serbian',
    'Seychellois',
    'Sierra Leonean',
    'Singaporean',
    'Slovak',
    'Slovenian',
    'Solomon Islander',
    'Somali',
    'South African',
    'South Korean',
    'South Sudanese',
    'Spanish',
    'Sri Lankan',
    'Sudanese',
    'Surinamese',
    'Swedish',
    'Swiss',
    'Syrian',
    'Taiwanese',
    'Tajik',
    'Tanzanian',
    'Thai',
    'Togolese',
    'Tongan',
    'Trinidadian or Tobagonian',
    'Tunisian',
    'Turkish',
    'Turkmen',
    'Tuvaluan',
    'Ugandan',
    'Ukrainian',
    'Uruguayan',
    'Uzbek',
    'Vanuatuan',
    'Venezuelan',
    'Vietnamese',
    'Yemeni',
    'Zambian',
    'Zimbabwean',
  ];

const nationalityToContinent: { [key: string]: string } = {
    Afghan: 'Asia',
    Albanian: 'Europe',
    Algerian: 'Africa',
    American: 'North America',
    Andorran: 'Europe',
    Angolan: 'Africa',
    'Antiguan or Barbudan': 'North America',
    Argentine: 'South America',
    Armenian: 'Asia',
    Australian: 'Australia',
    Austrian: 'Europe',
    Azerbaijani: 'Asia',
    Bahamian: 'North America',
    Bahraini: 'Asia',
    Bangladeshi: 'Asia',
    Barbadian: 'North America',
    Belarusian: 'Europe',
    Belgian: 'Europe',
    Belizean: 'North America',
    Beninese: 'Africa',
    Bhutanese: 'Asia',
    Bolivian: 'South America',
    'Bosnian or Herzegovinian': 'Europe',
    Botswanan: 'Africa',
    Brazilian: 'South America',
    British: 'Europe',
    Bruneian: 'Asia',
    Bulgarian: 'Europe',
    Burkinabé: 'Africa',
    Burmese: 'Asia',
    Burundian: 'Africa',
    'Cabo Verdean': 'Africa',
    Cambodian: 'Asia',
    Cameroonian: 'Africa',
    Canadian: 'North America',
    'Central African': 'Africa',
    Chadian: 'Africa',
    Chilean: 'South America',
    Chinese: 'Asia',
    Colombian: 'South America',
    Comoran: 'Africa',
    'Congolese (Congo-Brazzaville)': 'Africa',
    'Congolese (Congo-Kinshasa)': 'Africa',
    'Costa Rican': 'North America',
    Croatian: 'Europe',
    Cuban: 'North America',
    Cypriot: 'Asia',
    Czech: 'Europe',
    Danish: 'Europe',
    Djiboutian: 'Africa',
    Dominican: 'North America',
    'Dominican (Dominican Republic)': 'North America',
    Dutch: 'Europe',
    'East Timorese': 'Asia',
    Ecuadorean: 'South America',
    Egyptian: 'Africa',
    Emirati: 'Asia',
    'Equatorial Guinean': 'Africa',
    Eritrean: 'Africa',
    Estonian: 'Europe',
    Eswatini: 'Africa',
    Ethiopian: 'Africa',
    Fijian: 'Australia',
    Filipino: 'Asia',
    Finnish: 'Europe',
    French: 'Europe',
    Gabonese: 'Africa',
    Gambian: 'Africa',
    Georgian: 'Asia',
    German: 'Europe',
    Ghanaian: 'Africa',
    Greek: 'Europe',
    Grenadian: 'North America',
    Guatemalan: 'North America',
    Guinean: 'Africa',
    'Guinea-Bissauan': 'Africa',
    Guyanese: 'South America',
    Haitian: 'North America',
    Honduran: 'North America',
    Hungarian: 'Europe',
    Icelander: 'Europe',
    Indian: 'Asia',
    Indonesian: 'Asia',
    Iranian: 'Asia',
    Iraqi: 'Asia',
    Irish: 'Europe',
    Israeli: 'Asia',
    Italian: 'Europe',
    Ivorian: 'Africa',
    Jamaican: 'North America',
    Japanese: 'Asia',
    Jordanian: 'Asia',
    Kazakh: 'Asia',
    Kenyan: 'Africa',
    Kiribati: 'Australia',
    Kuwaiti: 'Asia',
    Kyrgyz: 'Asia',
    Laotian: 'Asia',
    Latvian: 'Europe',
    Lebanese: 'Asia',
    Lesotho: 'Africa',
    Liberian: 'Africa',
    Libyan: 'Africa',
    Liechtenstein: 'Europe',
    Lithuanian: 'Europe',
    Luxembourgish: 'Europe',
    Macedonian: 'Europe',
    Malagasy: 'Africa',
    Malawian: 'Africa',
    Malaysian: 'Asia',
    Maldivian: 'Asia',
    Malian: 'Africa',
    Maltese: 'Europe',
    Marshallese: 'Australia',
    Mauritanian: 'Africa',
    Mauritian: 'Africa',
    Mexican: 'North America',
    Micronesian: 'Australia',
    Moldovan: 'Europe',
    Monacan: 'Europe',
    Mongolian: 'Asia',
    Montenegrin: 'Europe',
    Moroccan: 'Africa',
    Mozambican: 'Africa',
    Namibian: 'Africa',
    Nauruan: 'Australia',
    Nepalese: 'Asia',
    'New Zealander': 'Australia',
    Nicaraguan: 'North America',
    Nigerien: 'Africa',
    Nigerian: 'Africa',
    'North Korean': 'Asia',
    Norwegian: 'Europe',
    Omani: 'Asia',
    Pakistani: 'Asia',
    Palauan: 'Australia',
    Palestinian: 'Asia',
    Panamanian: 'North America',
    'Papua New Guinean': 'Australia',
    Paraguayan: 'South America',
    Peruvian: 'South America',
    Polish: 'Europe',
    Portuguese: 'Europe',
    Qatari: 'Asia',
    Romanian: 'Europe',
    Russian: 'Europe',
    Rwandan: 'Africa',
    'Saint Kitts and Nevis': 'North America',
    'Saint Lucian': 'North America',
    'Saint Vincentian': 'North America',
    Samoan: 'Australia',
    'San Marinese': 'Europe',
    'Sao Tomean': 'Africa',
    Saudi: 'Asia',
    Senegalese: 'Africa',
    Serbian: 'Europe',
    Seychellois: 'Africa',
    'Sierra Leonean': 'Africa',
    Singaporean: 'Asia',
    Slovak: 'Europe',
    Slovenian: 'Europe',
    'Solomon Islander': 'Australia',
    Somali: 'Africa',
    'South African': 'Africa',
    'South Korean': 'Asia',
    'South Sudanese': 'Africa',
    Spanish: 'Europe',
    'Sri Lankan': 'Asia',
    Sudanese: 'Africa',
    Surinamese: 'South America',
    Swazi: 'Africa',
    Swedish: 'Europe',
    Swiss: 'Europe',
    Syrian: 'Asia',
    Taiwanese: 'Asia',
    Tajik: 'Asia',
    Tanzanian: 'Africa',
    Thai: 'Asia',
    Togolese: 'Africa',
    Tongan: 'Australia',
    'Trinidadian or Tobagonian': 'North America',
    Tunisian: 'Africa',
    Turkish: 'Asia',
    Turkmen: 'Asia',
    Tuvaluan: 'Australia',
    Ugandan: 'Africa',
    Ukrainian: 'Europe',
    Uruguayan: 'South America',
    Uzbek: 'Asia',
    Vanuatuan: 'Australia',
    Venezuelan: 'South America',
    Vietnamese: 'Asia',
    Yemeni: 'Asia',
    Zambian: 'Africa',
    Zimbabwean: 'Africa',
  };

export const getContinentFromNationality = (nationality: string): string => {
    return nationalityToContinent[nationality] || '';
  };